# analysis.R
# KC1 Defect Prediction – Descriptive Statistics, Correlation & Regression
# Author: Generated by ChatGPT o3 – 2025‑06‑30

## ---- Load libraries ----------------------------------------------------
suppressPackageStartupMessages({
  library(tidyverse)
  library(readxl)
  library(PerformanceAnalytics)
  library(ggpubr)
})

## ---- Read data ---------------------------------------------------------
# Adjust the path if your dataset is elsewhere
data <- read_excel("KC1_classlevel_numdefect.xlsx")

## ---- Select numeric columns -------------------------------------------
num_cols <- data %>% dplyr::select(where(is.numeric))

## ---- Descriptive statistics -------------------------------------------
# Central tendency and dispersion
desc_tbl <- num_cols %>% 
  summarise(across(everything(),
                   list(mean   = ~mean(., na.rm = TRUE),
                        median = ~median(., na.rm = TRUE),
                        sd     = ~sd(., na.rm = TRUE),
                        min    = ~min(., na.rm = TRUE),
                        max    = ~max(., na.rm = TRUE),
                        n      = ~length(.[!is.na(.)])),
                   .names = "{.col}_{.fn}"))

# Mode helper
get_mode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}
mode_tbl <- num_cols %>% summarise(across(everything(), get_mode, .names = "{.col}_mode"))

## ---- Save descriptive tables ------------------------------------------
write.csv(desc_tbl, "descriptive_stats.csv", row.names = FALSE)
write.csv(mode_tbl, "mode_stats.csv", row.names = FALSE)

## ---- Visualisations: histograms & boxplots ----------------------------
message("Generating histograms, density plots and boxplots …")
pdf("descriptive_plots.pdf")
for (col in names(num_cols)) {
  g1 <- ggplot(data, aes_string(x = col)) +
    geom_histogram(aes(y = ..density..), bins = 30, alpha = 0.6) +
    geom_density(colour = "blue", linewidth = 0.8) +
    ggtitle(paste("Histogram & Density –", col))
  print(g1)

  g2 <- ggplot(data, aes_string(y = col)) +
    geom_boxplot(fill = "grey80") +
    ggtitle(paste("Boxplot –", col))
  print(g2)
}
dev.off()

## ---- Normality tests ---------------------------------------------------
shapiro_tbl <- num_cols %>% summarise(across(everything(),
                                             ~shapiro.test(.)$p.value,
                                             .names = "{.col}_shapiro_p"))
write.csv(shapiro_tbl, "normality_tests.csv", row.names = FALSE)

## ---- Correlation matrix & scatter plots -------------------------------
corr_mat <- cor(num_cols, use = "complete.obs")
png("correlation_matrix.png", width = 1000, height = 1000)
chart.Correlation(num_cols, histogram = TRUE, pch = 19, main = "Correlation Matrix")
dev.off()

# Variables most correlated (absolute) with NUMDEFECTS
cor_vec <- sort(abs(corr_mat[,"NUMDEFECTS"]), decreasing = TRUE)
top_vars <- names(cor_vec)[2:4]  # ignore NUMDEFECTS itself

message("Top correlated predictors with NUMDEFECTS: ", paste(top_vars, collapse = ", "))

pdf("scatter_plots.pdf")
for (v in top_vars) {
  g <- ggplot(data, aes_string(x = v, y = "NUMDEFECTS")) +
    geom_point(alpha = 0.6) +
    geom_smooth(method = "lm", se = FALSE, colour = "red") +
    ggtitle(paste("NUMDEFECTS ×", v))
  print(g)
}
dev.off()

## ---- Regression model --------------------------------------------------
formula_txt <- paste("NUMDEFECTS ~", paste(top_vars, collapse = " + "))
model <- lm(as.formula(formula_txt), data = data)
summary(model)

## ---- Residual diagnostics ---------------------------------------------
png("residual_plots.png", width = 900, height = 900)
par(mfrow = c(2,2))
plot(model)
dev.off()

## ---- Save model --------------------------------------------------------
saveRDS(model, file = "defect_model.rds")
message("Model saved to defect_model.rds")
